package com.bolin.logistics.model;

import java.util.ArrayList;
import java.util.List;

public class CarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public CarExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdIsNull() {
            addCriterion("warehouse_id is null");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdIsNotNull() {
            addCriterion("warehouse_id is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdEqualTo(Integer value) {
            addCriterion("warehouse_id =", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdNotEqualTo(Integer value) {
            addCriterion("warehouse_id <>", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdGreaterThan(Integer value) {
            addCriterion("warehouse_id >", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("warehouse_id >=", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdLessThan(Integer value) {
            addCriterion("warehouse_id <", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("warehouse_id <=", value, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdIn(List<Integer> values) {
            addCriterion("warehouse_id in", values, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdNotIn(List<Integer> values) {
            addCriterion("warehouse_id not in", values, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdBetween(Integer value1, Integer value2) {
            addCriterion("warehouse_id between", value1, value2, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andWarehouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("warehouse_id not between", value1, value2, "warehouseId");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceIsNull() {
            addCriterion("drive_licence is null");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceIsNotNull() {
            addCriterion("drive_licence is not null");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceEqualTo(String value) {
            addCriterion("drive_licence =", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotEqualTo(String value) {
            addCriterion("drive_licence <>", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceGreaterThan(String value) {
            addCriterion("drive_licence >", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceGreaterThanOrEqualTo(String value) {
            addCriterion("drive_licence >=", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceLessThan(String value) {
            addCriterion("drive_licence <", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceLessThanOrEqualTo(String value) {
            addCriterion("drive_licence <=", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceLike(String value) {
            addCriterion("drive_licence like", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotLike(String value) {
            addCriterion("drive_licence not like", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceIn(List<String> values) {
            addCriterion("drive_licence in", values, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotIn(List<String> values) {
            addCriterion("drive_licence not in", values, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceBetween(String value1, String value2) {
            addCriterion("drive_licence between", value1, value2, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotBetween(String value1, String value2) {
            addCriterion("drive_licence not between", value1, value2, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardIsNull() {
            addCriterion("insurance_card is null");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardIsNotNull() {
            addCriterion("insurance_card is not null");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardEqualTo(String value) {
            addCriterion("insurance_card =", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardNotEqualTo(String value) {
            addCriterion("insurance_card <>", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardGreaterThan(String value) {
            addCriterion("insurance_card >", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardGreaterThanOrEqualTo(String value) {
            addCriterion("insurance_card >=", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardLessThan(String value) {
            addCriterion("insurance_card <", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardLessThanOrEqualTo(String value) {
            addCriterion("insurance_card <=", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardLike(String value) {
            addCriterion("insurance_card like", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardNotLike(String value) {
            addCriterion("insurance_card not like", value, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardIn(List<String> values) {
            addCriterion("insurance_card in", values, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardNotIn(List<String> values) {
            addCriterion("insurance_card not in", values, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardBetween(String value1, String value2) {
            addCriterion("insurance_card between", value1, value2, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andInsuranceCardNotBetween(String value1, String value2) {
            addCriterion("insurance_card not between", value1, value2, "insuranceCard");
            return (Criteria) this;
        }

        public Criteria andRunLicenceIsNull() {
            addCriterion("run_licence is null");
            return (Criteria) this;
        }

        public Criteria andRunLicenceIsNotNull() {
            addCriterion("run_licence is not null");
            return (Criteria) this;
        }

        public Criteria andRunLicenceEqualTo(String value) {
            addCriterion("run_licence =", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceNotEqualTo(String value) {
            addCriterion("run_licence <>", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceGreaterThan(String value) {
            addCriterion("run_licence >", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceGreaterThanOrEqualTo(String value) {
            addCriterion("run_licence >=", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceLessThan(String value) {
            addCriterion("run_licence <", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceLessThanOrEqualTo(String value) {
            addCriterion("run_licence <=", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceLike(String value) {
            addCriterion("run_licence like", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceNotLike(String value) {
            addCriterion("run_licence not like", value, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceIn(List<String> values) {
            addCriterion("run_licence in", values, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceNotIn(List<String> values) {
            addCriterion("run_licence not in", values, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceBetween(String value1, String value2) {
            addCriterion("run_licence between", value1, value2, "runLicence");
            return (Criteria) this;
        }

        public Criteria andRunLicenceNotBetween(String value1, String value2) {
            addCriterion("run_licence not between", value1, value2, "runLicence");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeIsNull() {
            addCriterion("allow_carry_volume is null");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeIsNotNull() {
            addCriterion("allow_carry_volume is not null");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeEqualTo(Double value) {
            addCriterion("allow_carry_volume =", value, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeNotEqualTo(Double value) {
            addCriterion("allow_carry_volume <>", value, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeGreaterThan(Double value) {
            addCriterion("allow_carry_volume >", value, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("allow_carry_volume >=", value, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeLessThan(Double value) {
            addCriterion("allow_carry_volume <", value, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeLessThanOrEqualTo(Double value) {
            addCriterion("allow_carry_volume <=", value, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeIn(List<Double> values) {
            addCriterion("allow_carry_volume in", values, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeNotIn(List<Double> values) {
            addCriterion("allow_carry_volume not in", values, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeBetween(Double value1, Double value2) {
            addCriterion("allow_carry_volume between", value1, value2, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryVolumeNotBetween(Double value1, Double value2) {
            addCriterion("allow_carry_volume not between", value1, value2, "allowCarryVolume");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightIsNull() {
            addCriterion("allow_carry_weight is null");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightIsNotNull() {
            addCriterion("allow_carry_weight is not null");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightEqualTo(Double value) {
            addCriterion("allow_carry_weight =", value, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightNotEqualTo(Double value) {
            addCriterion("allow_carry_weight <>", value, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightGreaterThan(Double value) {
            addCriterion("allow_carry_weight >", value, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("allow_carry_weight >=", value, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightLessThan(Double value) {
            addCriterion("allow_carry_weight <", value, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightLessThanOrEqualTo(Double value) {
            addCriterion("allow_carry_weight <=", value, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightIn(List<Double> values) {
            addCriterion("allow_carry_weight in", values, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightNotIn(List<Double> values) {
            addCriterion("allow_carry_weight not in", values, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightBetween(Double value1, Double value2) {
            addCriterion("allow_carry_weight between", value1, value2, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andAllowCarryWeightNotBetween(Double value1, Double value2) {
            addCriterion("allow_carry_weight not between", value1, value2, "allowCarryWeight");
            return (Criteria) this;
        }

        public Criteria andCarLengthIsNull() {
            addCriterion("car_length is null");
            return (Criteria) this;
        }

        public Criteria andCarLengthIsNotNull() {
            addCriterion("car_length is not null");
            return (Criteria) this;
        }

        public Criteria andCarLengthEqualTo(Double value) {
            addCriterion("car_length =", value, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthNotEqualTo(Double value) {
            addCriterion("car_length <>", value, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthGreaterThan(Double value) {
            addCriterion("car_length >", value, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("car_length >=", value, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthLessThan(Double value) {
            addCriterion("car_length <", value, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthLessThanOrEqualTo(Double value) {
            addCriterion("car_length <=", value, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthIn(List<Double> values) {
            addCriterion("car_length in", values, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthNotIn(List<Double> values) {
            addCriterion("car_length not in", values, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthBetween(Double value1, Double value2) {
            addCriterion("car_length between", value1, value2, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarLengthNotBetween(Double value1, Double value2) {
            addCriterion("car_length not between", value1, value2, "carLength");
            return (Criteria) this;
        }

        public Criteria andCarWidthIsNull() {
            addCriterion("car_width is null");
            return (Criteria) this;
        }

        public Criteria andCarWidthIsNotNull() {
            addCriterion("car_width is not null");
            return (Criteria) this;
        }

        public Criteria andCarWidthEqualTo(Double value) {
            addCriterion("car_width =", value, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthNotEqualTo(Double value) {
            addCriterion("car_width <>", value, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthGreaterThan(Double value) {
            addCriterion("car_width >", value, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthGreaterThanOrEqualTo(Double value) {
            addCriterion("car_width >=", value, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthLessThan(Double value) {
            addCriterion("car_width <", value, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthLessThanOrEqualTo(Double value) {
            addCriterion("car_width <=", value, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthIn(List<Double> values) {
            addCriterion("car_width in", values, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthNotIn(List<Double> values) {
            addCriterion("car_width not in", values, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthBetween(Double value1, Double value2) {
            addCriterion("car_width between", value1, value2, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarWidthNotBetween(Double value1, Double value2) {
            addCriterion("car_width not between", value1, value2, "carWidth");
            return (Criteria) this;
        }

        public Criteria andCarHeightIsNull() {
            addCriterion("car_height is null");
            return (Criteria) this;
        }

        public Criteria andCarHeightIsNotNull() {
            addCriterion("car_height is not null");
            return (Criteria) this;
        }

        public Criteria andCarHeightEqualTo(Double value) {
            addCriterion("car_height =", value, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightNotEqualTo(Double value) {
            addCriterion("car_height <>", value, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightGreaterThan(Double value) {
            addCriterion("car_height >", value, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("car_height >=", value, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightLessThan(Double value) {
            addCriterion("car_height <", value, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightLessThanOrEqualTo(Double value) {
            addCriterion("car_height <=", value, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightIn(List<Double> values) {
            addCriterion("car_height in", values, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightNotIn(List<Double> values) {
            addCriterion("car_height not in", values, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightBetween(Double value1, Double value2) {
            addCriterion("car_height between", value1, value2, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarHeightNotBetween(Double value1, Double value2) {
            addCriterion("car_height not between", value1, value2, "carHeight");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoIsNull() {
            addCriterion("car_frame_no is null");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoIsNotNull() {
            addCriterion("car_frame_no is not null");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoEqualTo(String value) {
            addCriterion("car_frame_no =", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoNotEqualTo(String value) {
            addCriterion("car_frame_no <>", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoGreaterThan(String value) {
            addCriterion("car_frame_no >", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoGreaterThanOrEqualTo(String value) {
            addCriterion("car_frame_no >=", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoLessThan(String value) {
            addCriterion("car_frame_no <", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoLessThanOrEqualTo(String value) {
            addCriterion("car_frame_no <=", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoLike(String value) {
            addCriterion("car_frame_no like", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoNotLike(String value) {
            addCriterion("car_frame_no not like", value, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoIn(List<String> values) {
            addCriterion("car_frame_no in", values, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoNotIn(List<String> values) {
            addCriterion("car_frame_no not in", values, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoBetween(String value1, String value2) {
            addCriterion("car_frame_no between", value1, value2, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarFrameNoNotBetween(String value1, String value2) {
            addCriterion("car_frame_no not between", value1, value2, "carFrameNo");
            return (Criteria) this;
        }

        public Criteria andCarNoIsNull() {
            addCriterion("car_no is null");
            return (Criteria) this;
        }

        public Criteria andCarNoIsNotNull() {
            addCriterion("car_no is not null");
            return (Criteria) this;
        }

        public Criteria andCarNoEqualTo(String value) {
            addCriterion("car_no =", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotEqualTo(String value) {
            addCriterion("car_no <>", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoGreaterThan(String value) {
            addCriterion("car_no >", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoGreaterThanOrEqualTo(String value) {
            addCriterion("car_no >=", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoLessThan(String value) {
            addCriterion("car_no <", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoLessThanOrEqualTo(String value) {
            addCriterion("car_no <=", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoLike(String value) {
            addCriterion("car_no like", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotLike(String value) {
            addCriterion("car_no not like", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoIn(List<String> values) {
            addCriterion("car_no in", values, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotIn(List<String> values) {
            addCriterion("car_no not in", values, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoBetween(String value1, String value2) {
            addCriterion("car_no between", value1, value2, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotBetween(String value1, String value2) {
            addCriterion("car_no not between", value1, value2, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNull() {
            addCriterion("car_type is null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNotNull() {
            addCriterion("car_type is not null");
            return (Criteria) this;
        }

        public Criteria andCarTypeEqualTo(String value) {
            addCriterion("car_type =", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotEqualTo(String value) {
            addCriterion("car_type <>", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThan(String value) {
            addCriterion("car_type >", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThanOrEqualTo(String value) {
            addCriterion("car_type >=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThan(String value) {
            addCriterion("car_type <", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThanOrEqualTo(String value) {
            addCriterion("car_type <=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLike(String value) {
            addCriterion("car_type like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotLike(String value) {
            addCriterion("car_type not like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeIn(List<String> values) {
            addCriterion("car_type in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotIn(List<String> values) {
            addCriterion("car_type not in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeBetween(String value1, String value2) {
            addCriterion("car_type between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotBetween(String value1, String value2) {
            addCriterion("car_type not between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 07 19:51:04 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}