package com.bolin.logistics.model;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.id
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.province
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.city
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.detail_address
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.gmt_create
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.gmt_modified
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.id
     *
     * @return the value of location.id
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.id
     *
     * @param id the value for location.id
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.province
     *
     * @return the value of location.province
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.province
     *
     * @param province the value for location.province
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.city
     *
     * @return the value of location.city
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.city
     *
     * @param city the value for location.city
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.detail_address
     *
     * @return the value of location.detail_address
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.detail_address
     *
     * @param detailAddress the value for location.detail_address
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.gmt_create
     *
     * @return the value of location.gmt_create
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.gmt_create
     *
     * @param gmtCreate the value for location.gmt_create
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.gmt_modified
     *
     * @return the value of location.gmt_modified
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.gmt_modified
     *
     * @param gmtModified the value for location.gmt_modified
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}