package com.bolin.logistics.model;

public class TransferInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.goods_info_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long goodsInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.car_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.goods_bill_code
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private String goodsBillCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.accept_station
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private String acceptStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.carriage
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Double carriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.operate_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long operateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.fact_deal_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long factDealDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.predelivery_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long predeliveryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.send_goods_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long sendGoodsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.fetch_goods_mode
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Integer fetchGoodsMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.insurance
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Double insurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.receive_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private String receiveUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.send_goods_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private String sendGoodsUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.remark
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.status
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.gmt_create
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.gmt_modified
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.id
     *
     * @return the value of transfer_info.id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.id
     *
     * @param id the value for transfer_info.id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.goods_info_id
     *
     * @return the value of transfer_info.goods_info_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getGoodsInfoId() {
        return goodsInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.goods_info_id
     *
     * @param goodsInfoId the value for transfer_info.goods_info_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setGoodsInfoId(Long goodsInfoId) {
        this.goodsInfoId = goodsInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.car_id
     *
     * @return the value of transfer_info.car_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.car_id
     *
     * @param carId the value for transfer_info.car_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setCarId(Long carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.goods_bill_code
     *
     * @return the value of transfer_info.goods_bill_code
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public String getGoodsBillCode() {
        return goodsBillCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.goods_bill_code
     *
     * @param goodsBillCode the value for transfer_info.goods_bill_code
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setGoodsBillCode(String goodsBillCode) {
        this.goodsBillCode = goodsBillCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.accept_station
     *
     * @return the value of transfer_info.accept_station
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public String getAcceptStation() {
        return acceptStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.accept_station
     *
     * @param acceptStation the value for transfer_info.accept_station
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setAcceptStation(String acceptStation) {
        this.acceptStation = acceptStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.carriage
     *
     * @return the value of transfer_info.carriage
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Double getCarriage() {
        return carriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.carriage
     *
     * @param carriage the value for transfer_info.carriage
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setCarriage(Double carriage) {
        this.carriage = carriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.operate_user_id
     *
     * @return the value of transfer_info.operate_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getOperateUserId() {
        return operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.operate_user_id
     *
     * @param operateUserId the value for transfer_info.operate_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setOperateUserId(Long operateUserId) {
        this.operateUserId = operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.fact_deal_date
     *
     * @return the value of transfer_info.fact_deal_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getFactDealDate() {
        return factDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.fact_deal_date
     *
     * @param factDealDate the value for transfer_info.fact_deal_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setFactDealDate(Long factDealDate) {
        this.factDealDate = factDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.predelivery_date
     *
     * @return the value of transfer_info.predelivery_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getPredeliveryDate() {
        return predeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.predelivery_date
     *
     * @param predeliveryDate the value for transfer_info.predelivery_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setPredeliveryDate(Long predeliveryDate) {
        this.predeliveryDate = predeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.send_goods_date
     *
     * @return the value of transfer_info.send_goods_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getSendGoodsDate() {
        return sendGoodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.send_goods_date
     *
     * @param sendGoodsDate the value for transfer_info.send_goods_date
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setSendGoodsDate(Long sendGoodsDate) {
        this.sendGoodsDate = sendGoodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.fetch_goods_mode
     *
     * @return the value of transfer_info.fetch_goods_mode
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Integer getFetchGoodsMode() {
        return fetchGoodsMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.fetch_goods_mode
     *
     * @param fetchGoodsMode the value for transfer_info.fetch_goods_mode
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setFetchGoodsMode(Integer fetchGoodsMode) {
        this.fetchGoodsMode = fetchGoodsMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.insurance
     *
     * @return the value of transfer_info.insurance
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Double getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.insurance
     *
     * @param insurance the value for transfer_info.insurance
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setInsurance(Double insurance) {
        this.insurance = insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.receive_user_id
     *
     * @return the value of transfer_info.receive_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public String getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.receive_user_id
     *
     * @param receiveUserId the value for transfer_info.receive_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setReceiveUserId(String receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.send_goods_user_id
     *
     * @return the value of transfer_info.send_goods_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public String getSendGoodsUserId() {
        return sendGoodsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.send_goods_user_id
     *
     * @param sendGoodsUserId the value for transfer_info.send_goods_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setSendGoodsUserId(String sendGoodsUserId) {
        this.sendGoodsUserId = sendGoodsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.remark
     *
     * @return the value of transfer_info.remark
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.remark
     *
     * @param remark the value for transfer_info.remark
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.status
     *
     * @return the value of transfer_info.status
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.status
     *
     * @param status the value for transfer_info.status
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.gmt_create
     *
     * @return the value of transfer_info.gmt_create
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.gmt_create
     *
     * @param gmtCreate the value for transfer_info.gmt_create
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.gmt_modified
     *
     * @return the value of transfer_info.gmt_modified
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.gmt_modified
     *
     * @param gmtModified the value for transfer_info.gmt_modified
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}