package com.bolin.logistics.model;

public class Warehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.director_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long directorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.location_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.description
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.gmt_create
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.gmt_modified
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.id
     *
     * @return the value of warehouse.id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.id
     *
     * @param id the value for warehouse.id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.director_user_id
     *
     * @return the value of warehouse.director_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getDirectorUserId() {
        return directorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.director_user_id
     *
     * @param directorUserId the value for warehouse.director_user_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setDirectorUserId(Long directorUserId) {
        this.directorUserId = directorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.location_id
     *
     * @return the value of warehouse.location_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.location_id
     *
     * @param locationId the value for warehouse.location_id
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.description
     *
     * @return the value of warehouse.description
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.description
     *
     * @param description the value for warehouse.description
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.gmt_create
     *
     * @return the value of warehouse.gmt_create
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.gmt_create
     *
     * @param gmtCreate the value for warehouse.gmt_create
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.gmt_modified
     *
     * @return the value of warehouse.gmt_modified
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.gmt_modified
     *
     * @param gmtModified the value for warehouse.gmt_modified
     *
     * @mbg.generated Wed Mar 09 00:49:58 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}