package com.bolin.logistics.mapper;

import com.bolin.logistics.model.Location;
import com.bolin.logistics.model.LocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    long countByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int deleteByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    List<Location> selectByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    Location selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByPrimaryKey(Location record);
}