package com.bolin.logistics.mapper;

import com.bolin.logistics.model.Pay;
import com.bolin.logistics.model.PayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    long countByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int deleteByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    List<Pay> selectByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    Pay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int updateByExampleSelective(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int updateByExample(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbg.generated Wed Mar 09 17:07:10 CST 2022
     */
    int updateByPrimaryKey(Pay record);
}