package com.bolin.logistics.mapper;

import com.bolin.logistics.model.TransferInfo;
import com.bolin.logistics.model.TransferInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    long countByExample(TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int deleteByExample(TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int insert(TransferInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int insertSelective(TransferInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    List<TransferInfo> selectByExample(TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    TransferInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByExampleSelective(@Param("record") TransferInfo record, @Param("example") TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByExample(@Param("record") TransferInfo record, @Param("example") TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByPrimaryKeySelective(TransferInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Mar 07 19:51:04 CST 2022
     */
    int updateByPrimaryKey(TransferInfo record);
}